create TABLE DATA_CLIENT (
  ID VARCHAR2(32) not null,
  CLIENT_TIME VARCHAR2(64),
  PASSWORD VARCHAR2(100),
  ORGANIZATION VARCHAR2(32),
  AREA VARCHAR2(32),
  CREATE_ID VARCHAR2(32),
  CREATE_TIME TIMESTAMP(6),
  UPDATE_ID VARCHAR2(32),
  UPDATE_TIME TIMESTAMP(6),
  DEL_FLAG CHAR(1) default 0
  ,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX DATA_CLIENT_ID_PK ON DATA_CLIENT (ID ASC);


create TABLE ORGANIZATION (
  ID VARCHAR2(32) PRIMARY KEY NOT NULL,
  ORGAN_NAME VARCHAR2(64),
  ORGAN_ENAME VARCHAR2(64),
  ORGAN_CODE VARCHAR2(64),
  CREATE_ID VARCHAR2(32),
  CREATE_TIME TIMESTAMP(6),
  UPDATE_ID VARCHAR2(32),
  UPDATE_TIME TIMESTAMP(6),
  DEL_FLAG CHAR(1) default 0
);

create TABLE AREA (
  ID VARCHAR2(32) PRIMARY KEY NOT NULL,
  AREA_NAME VARCHAR2(64),
  AREA_ENAME VARCHAR2(64),
  AREA_CODE VARCHAR2(64),
  CREATE_ID VARCHAR2(32),
  CREATE_TIME TIMESTAMP(6),
  UPDATE_ID VARCHAR2(32),
  UPDATE_TIME TIMESTAMP(6),
  DEL_FLAG CHAR(1) default 0
);