
/* Drop Tables */

DROP TABLE T_SIIP_DRUGINSTORE CASCADE CONSTRAINTS;
DROP TABLE T_SIIP_DRUGINSTOREDETAIL CASCADE CONSTRAINTS;
DROP TABLE T_SIIP_DRUGOUTSTORE CASCADE CONSTRAINTS;
DROP TABLE T_SIIP_DRUGOUTSTOREDETAIL CASCADE CONSTRAINTS;
DROP TABLE T_SIIP_DRUGSTORAGESTOCK CASCADE CONSTRAINTS;
DROP TABLE T_SIIP_INVDRUGSTORE CASCADE CONSTRAINTS;
DROP TABLE T_SIIP_INVDRUGSTOREDETAIL CASCADE CONSTRAINTS;
DROP TABLE T_SIIP_SENDCOLLECTDETAIL CASCADE CONSTRAINTS;
DROP TABLE T_SIIP_SENDLIST CASCADE CONSTRAINTS;
DROP TABLE T_SIIP_SENDLISTCOLLECT CASCADE CONSTRAINTS;
DROP TABLE T_SIIP_SENDLISTDETAIL CASCADE CONSTRAINTS;
DROP TABLE T_SIIP_RECIPE CASCADE CONSTRAINTS;


CREATE TABLE T_SIIP_RECIPE
(
  AREA                  VARCHAR2(128),
  INSTITUTION           VARCHAR2(128),
  C_RECIPECD            VARCHAR2(30) NOT NULL,
  C_RECIPECDOLD         VARCHAR2(30),
  D_RECIPEEXPIREDATE    DATE,
  C_RECIPETYPE          VARCHAR2(2),
  N_RECIPESORT          NUMBER(1, 0),
  N_SPECIALFLG          NUMBER(1, 0),
  N_RECIPECOUNT         NUMBER(10, 0),
  N_RECIPEAMOUNT        NUMBER(12, 4),
  C_RECIPEENTEROPER     NVARCHAR2(20),
  D_DOCTORDATETIME      DATE,
  C_DOCTORCD            NVARCHAR2(160),
  C_DOCTORNAME          NVARCHAR2(400),
  C_DOCTORDEPTCD        VARCHAR2(10),
  C_DOCTORDEPTNAME      NVARCHAR2(40),
  C_FEEOPER             VARCHAR2(20),
  D_FEEDATETIME         DATE,
  N_FEEAMOUNT           NUMBER(12, 4),
  C_PATIENTICD10CD      NVARCHAR2(20),
  C_PATIENTICD10NAME    NVARCHAR2(100),
  C_PATIENTICD10NOTES   NVARCHAR2(510),
  C_PATIENTID           VARCHAR2(50),
  C_PATIENTCARDCD       VARCHAR2(50),
  C_CITYCARDCD          VARCHAR2(50),
  C_PATIENTTIMES        NUMBER(10, 0),
  C_RECIPECDHIS         VARCHAR2(30),
  N_LEDGERNO            NUMBER(10, 0),
  C_PATIENTNAME         NVARCHAR2(40),
  C_PATIENTSEX          NVARCHAR2(4),
  C_PATIENTAGE          NVARCHAR2(40),
  C_PATIENTPHONE        NVARCHAR2(60),
  C_PATIENTWORKUNIT     NVARCHAR2(100),
  D_PATIENTBIRTHDAY     DATE,
  C_PATIENTSORTCD       NVARCHAR2(40),
  C_PATIENTSORTNAME     NVARCHAR2(40),
  N_PATIENTHEIGHT       NUMBER(3, 0),
  N_PATIENTWEIGHT       NUMBER(3, 0),
  N_RECIPESTATUS        NUMBER(1, 0),
  N_INTERFACESTATUS     NUMBER(1, 0),
  N_VIPFLG              NUMBER(1, 0),
  C_DOCTORADVICE        NVARCHAR2(510),
  D_ADDDATETIME         DATE,
  B_TWOCODE             BLOB,
  C_NOTESEX1            NVARCHAR2(100),
  C_NOTESEX2            NVARCHAR2(100),
  C_NOTESEX3            NVARCHAR2(100),
  C_NOTESEX4            NVARCHAR2(100),
  C_NOTESEX5            NVARCHAR2(100),
  C_STORECD             NVARCHAR2(10),
  C_UPTOPERCD           NVARCHAR2(20),
  C_UPTOPERNAME         NVARCHAR2(20),
  D_UPTDATETIME         DATE,
  C_ADJUSTCD            NVARCHAR2(40),
  C_ADJUSTNAME          NVARCHAR2(40),
  C_INVOICESERIALNUM    NVARCHAR2(40),
  N_INFUSIONRECIPEFLG   NUMBER(1, 0),
  N_EMERGENCYPATIENTFLG NUMBER(1, 0),
  N_INFUSIONBRINGBACK   NUMBER(1, 0),
  C_PATIENTNAMEPYCODE   VARCHAR2(20),
  N_WINDOWNO            NUMBER(2, 0),
  PRIMARY KEY (C_RECIPECD)
);

/* Create Tables */

CREATE TABLE T_SIIP_DRUGINSTORE
(
	-- 入库单号
	C_ACCEPTBILLCD nvarchar2(100) ,
	-- 创建者编号
	CREATORCD nvarchar2(40) ,
	-- 创建者名称
	CREATORNAME nvarchar2(40) ,
	-- 创建时间
	CREATETIME date ,
	-- 相关单号
	C_OUTSTOREBILLUPCD nvarchar2(100) ,
	-- 入库时间
	D_ACCEPTDATETIME date ,
	-- 入库类型
	C_ACCEPTTYPE nvarchar2(30) ,
	-- 单据处理状态 0:未处理 1:已处理 9:已删除
	N_DEELSTATUS number(2,0) ,
	-- 单据接口发送状态 0：未发送  1：已发送
	N_SENDSTATUS number(2,0) ,
	-- 相关部门编码
	C_SENDDEPTCD nvarchar2(40) ,
	-- 相关部门名称
	C_OUTSTORENAME nvarchar2(100) ,
	-- 入库药房编码
	C_ACCEPTDEPTCD nvarchar2(40) ,
	-- 入库药房名称
	C_INSTORENAME nvarchar2(100) ,
	-- 入库品种数
	N_ACCEPTCOUNT number(5,0) ,
	-- 药品总金额
	N_DRUGAMOUNT number(10,4) ,
	-- 入库操作员编码
	C_ACCEPTOPERCD nvarchar2(40),
	-- 修改操作员编码
	C_UPTOPERCD nvarchar2(40),
	-- 更新时间
	D_UPTDATETIME date,
	-- 入库操作员名称
	C_ACCEPTOPERNAME nvarchar2(40),
	-- 修改操作员名称
	C_UPTOPERNAME nvarchar2(40),
	-- 备注
	C_REMARK nvarchar2(100),
	-- 审核人姓名
	C_AUDITORNAME nvarchar2(40),
	-- 上架人姓名
	C_SHELFUPPEOPLE nvarchar2(40),
	-- 机构
	INSTITUTION varchar2(128) ,
	-- 区域
	area varchar2(128) 
);


CREATE TABLE T_SIIP_DRUGINSTOREDETAIL
(
	-- 序号
	ID nvarchar2(60) ,
	-- 创建者编号
	CREATORCD nvarchar2(40) ,
	-- 创建者名称
	CREATORNAME nvarchar2(40) ,
	-- 创建时间
	CREATETIME date ,
	-- 入库单号
	C_ACCEPTBILLCD nvarchar2(100) ,
	-- 药品编号
	C_DRUGCD nvarchar2(60) ,
	-- 药品商品名称
	C_TRADENAME nvarchar2(100) ,
	-- 药品通用名称
	C_COMMONNAME nvarchar2(100) ,
	-- 生产厂家名称
	C_FACTORYNAME nvarchar2(100) ,
	-- 药品规格
	C_DRUGSPEC nvarchar2(60),
	-- 剂型
	C_FIGURENAME nvarchar2(40) ,
	-- 批次编号
	C_BATCHCD nvarchar2(100) ,
	-- 批次详细信息
	C_BATCHDETAIL nvarchar2(600),
	-- 货位储存号
	C_POSITIONCD nvarchar2(100),
	-- 药品包装单位编码
	C_PACKUNITCD varchar2(40) ,
	-- 药品包装单位名称
	C_PACKUNITNAME nvarchar2(40) ,
	-- 药品出库明细表
	N_PACKUNITPRICE number(12,4) ,
	-- 药品使用单位单价
	N_USEUNITPRICE number(18,4) ,
	-- 药品使用单位编码
	C_USEUNITCD nvarchar2(40) ,
	-- 药品使用单位名称
	C_USEUNITNAME nvarchar2(40) ,
	-- 药品入库单位编码
	C_INSTOREUNITCD nvarchar2(40) ,
	-- 药品入库单位名称
	C_INSTOREUNITNAME nvarchar2(40) ,
	-- 药品入库单位单价
	N_INSTOREUNITPRICE number(12,4) ,
	-- 药品入库数量
	N_DRUGCOUNT number(5,0) ,
	-- 药品入库金额
	N_DRUGAMOUNT number(10,4) ,
	-- 更新时间
	D_UPTDATETIME date,
	-- 机构
	INSTITUTION varchar2(128) ,
	-- 区域
	area varchar2(128) 
);


CREATE TABLE T_SIIP_DRUGOUTSTORE
(
	-- 出库单号
	C_OUTBILLCD nvarchar2(40) ,
	-- 创建者编号
	CREATORCD nvarchar2(40) ,
	-- 创建者名称
	CREATORNAME nvarchar2(40) ,
	-- 创建时间
	CREATETIME date ,
	-- 相关单号
	C_INSTOREBILLUPCD nvarchar2(100) ,
	-- 出库时间
	D_OUTDATETIME date ,
	-- 出库类型
	C_OUTTYPE nvarchar2(30) ,
	-- 单据处理状态 0:未处理 1:已处理 9:已删除
	N_DEELSTATUS number(2,0) ,
	-- 单据接口发送状态
	N_SENDSTATUS number(2,0) ,
	-- 相关库房编码
	C_ACCEPTDEPTCD nvarchar2(20) ,
	-- 相关库房名称
	C_ACCEPTDEPTNAME nvarchar2(100) ,
	-- 出库药房编码
	C_OUTDEPTCD nvarchar2(20) ,
	-- 出库药房名称
	C_OUTDEPTNAME nvarchar2(100) ,
	-- 出库品种数
	N_OUTCOUNT number(5,0) ,
	-- 药品总金额
	N_DRUGAMOUNT number(10,4) ,
	-- 出库操作员编码
	C_OUTOPERCD nvarchar2(40),
	-- 相关操作员编码
	C_ACCEPTOPERCD nvarchar2(40),
	-- 修改操作员编码
	C_UPTOPERCD nvarchar2(40),
	-- 更新时间
	D_UPTDATETIME date,
	-- 出库操作员名称
	C_OUTOPERNAME nvarchar2(40),
	-- 相关操作员名称
	C_ACCEPTOPERNAME nvarchar2(40),
	-- 修改操作员名称
	C_UPTOPERNAME nvarchar2(40),
	-- 备注
	C_REMARK nvarchar2(100),
	-- 审核人姓名
	C_AUDITORNAME nvarchar2(40),
	-- 下架人姓名
	C_SHELFDOWNPEOPLE nvarchar2(40),
	-- 机构
	INSTITUTION varchar2(128) ,
	-- 区域
	area varchar2(128) 
);


CREATE TABLE T_SIIP_DRUGOUTSTOREDETAIL
(
	-- 序号
	ID nvarchar2(60) ,
	-- 出库单号
	C_OUTBILLCD nvarchar2(40) ,
	-- 创建者编号
	CREATORCD nvarchar2(40) ,
	-- 创建者名称
	CREATORNAME nvarchar2(40) ,
	-- 创建时间
	CREATETIME date ,
	-- 药品编号
	C_DRUGCD nvarchar2(60) ,
	-- 药品商品名称
	C_TRADENAME nvarchar2(100) ,
	-- 药品通用名称
	C_COMMONNAME nvarchar2(100) ,
	-- 生产厂家名称
	C_FACTORYNAME nvarchar2(100) ,
	-- 药品规格
	C_DRUGSPEC nvarchar2(60) ,
	-- 剂型
	C_FIGURENAME nvarchar2(40) ,
	-- 批次编号
	C_BATCHCD nvarchar2(100),
	-- 批次详细信息
	C_BATCHDETAIL nvarchar2(600),
	-- 货位储存号
	C_POSITIONCD nvarchar2(100),
	-- 药品包装单位编码
	C_PACKUNITCD varchar2(40) ,
	-- 药品包装单位名称
	C_PACKUNITNAME nvarchar2(40) ,
	-- 药品出库明细表
	N_PACKUNITPRICE number(12,4) ,
	-- 药品使用单位编码
	C_USEUNITCD nvarchar2(40),
	-- 药品使用单位名称
	C_USEUNITNAME nvarchar2(40) ,
	-- 药品使用单位单价
	N_USEUNITPRICE number(12,4) ,
	-- 药品出库单位编码
	C_OUTSTORECD nvarchar2(40) ,
	-- 药品出库单位名称
	C_OUTSTORENAME nvarchar2(40) ,
	-- 药品出库单位单价
	N_OUTSTOREPRICE number(12,4) ,
	-- 药品出库数量
	N_DRUGCOUNT number(5,0) ,
	-- 药品出库金额
	N_DRUGAMOUNT number(10,4) ,
	-- 更新时间
	D_UPTDATETIME date,
	-- 机构
	INSTITUTION varchar2(128) ,
	-- 区域
	area varchar2(128) 
);


CREATE TABLE T_SIIP_DRUGSTORAGESTOCK
(
	-- 序号
	ID nvarchar2(60) ,
	-- 药品编号
	C_DRUGCD nvarchar2(60) ,
	-- 入库单位编码
	C_DRUGUNITCD nvarchar2(40) ,
	-- 批次编号
	C_BATCHCD nvarchar2(100),
	-- 创建者编号
	CREATORCD nvarchar2(40) ,
	-- 创建者名称
	CREATORNAME nvarchar2(40) ,
	-- 创建时间
	CREATETIME date ,
	-- 部门编码
	D_NUMBER char(10) ,
	-- 库存量
	N_DRUGSTOCK number(12,2) ,
	-- 机构
	INSTITUTION varchar2(128) ,
	-- 区域
	area varchar2(128) 
);


CREATE TABLE T_SIIP_INVDRUGSTORE
(
	-- 盘点编号
	C_INVSTORECD nvarchar2(100) ,
	-- 创建者编号
	CREATORCD nvarchar2(40) ,
	-- 创建者名称
	CREATORNAME nvarchar2(40) ,
	-- 创建时间
	CREATETIME date ,
	-- 药房编号
	C_DRUGSTORECD nvarchar2(40) ,
	-- 药房名称
	C_DRUGSTORENAME nvarchar2(160),
	-- 单据处理状态 0:未处理 1:已处理 9:已删除
	N_DEELSTATUS number(2,0) ,
	-- 单据接口发送状态 0：未发送  1：已发送
	N_SENDSTATUS number(2,0),
	-- 盘存时间
	D_INVSTORETIME date,
	-- 盘点前总金额
	N_BEFOREINVAMOUT number(14,4) ,
	-- 盘点后总金额
	N_AFTERINVAMOUNT number(14,4),
	-- 更新时间
	D_UPTDATETIME date,
	-- 审核人姓名
	C_AUDITORNAME nvarchar2(40),
	-- 盘点人
	C_INVPERSONNAME nvarchar2(40),
	-- 药品品种数
	N_DRUGSCOUNT number(5,0),
	-- 区域
	area varchar2(128) ,
	-- 机构
	INSTITUTION varchar2(128) 
);


CREATE TABLE T_SIIP_INVDRUGSTOREDETAIL
(
	-- 序号
	ID nvarchar2(60) ,
	-- 盘点编号
	C_INVSTORECD nvarchar2(100) ,
	-- 创建者编号
	CREATORCD nvarchar2(40) ,
	-- 创建者名称
	CREATORNAME nvarchar2(40) ,
	-- 创建时间
	CREATETIME date ,
	-- 药品编号
	C_DRUGCD nvarchar2(60) ,
	-- 药品商品名称
	C_TRADENAME nvarchar2(100) ,
	-- 药品通用名称
	C_COMMONNAME nvarchar2(100) ,
	-- 药品规格
	C_DRUGSPEC nvarchar2(60) ,
	-- 剂型
	C_FIGURENAME nvarchar2(40) ,
	-- 生产厂家名称
	C_FACTORYNAME nvarchar2(100) ,
	-- 货位储存号
	C_POSITIONCD nvarchar2(100),
	-- 更新时间
	D_UPTDATETIME date,
	-- 药品盘点单位编码
	C_DRUGINVUNITCD nvarchar2(40) ,
	-- 药品盘点单位名称
	C_DRUGINVUNITNAME nvarchar2(40),
	-- 盘点前库存量
	N_OLDSTOCK number(12,2) ,
	-- 盘点后库存量
	N_REALSTOCK number(12,2),
	-- 盘点前总金额
	N_OLDAMOUNT number(14,4) ,
	-- 盘点后总金额
	N_REALAMOUNT number(14,4),
	-- 药品包装单位编码
	C_PACKUNITCD varchar2(40) ,
	-- 药品包装单位名称
	C_PACKUNITNAME nvarchar2(40) ,
	-- 药品使用单位编码
	C_USEUNITCD nvarchar2(40) ,
	-- 药品使用单位名称
	C_USEUNITNAME nvarchar2(40) ,
	-- 药品出库明细表
	N_PACKUNITPRICE number(12,4) ,
	-- 药品使用单位单价
	N_USEUNITPRICE number(18,4) ,
	-- 药品盘点单位单价
	N_INVUNITPRICE number(12,4) ,
	-- 到包装单位转换系数
	N_DRUGPACKMODULUS number(16,6),
	-- 区域
	area varchar2(128) ,
	-- 机构
	INSTITUTION varchar2(128) 
);


CREATE TABLE T_SIIP_SENDCOLLECTDETAIL
(
	-- 序号
	ID nvarchar2(60) ,
	-- 汇总单序号
	N_COLLECTID varchar2(60) ,
	-- 发药单流水号
	C_SENDLISTCD nvarchar2(60) ,
	-- 创建者编号
	CREATORCD nvarchar2(40) ,
	-- 创建者名称
	CREATORNAME nvarchar2(40) ,
	-- 创建时间
	CREATETIME date ,
	-- 病人ID号
	C_PATIENTID nvarchar2(100) ,
	-- 病人姓名
	C_PATIENTNAME nvarchar2(36) ,
	-- 病人姓名拼音码
	C_PATIENTNAMEPYCODE nvarchar2(36),
	-- 药品编号
	C_DRUGCD nvarchar2(60) ,
	-- 药品通用名称
	C_COMMONNAME nvarchar2(100) ,
	-- 药品商品名称
	C_TRADENAME nvarchar2(100) ,
	-- 药品规格
	C_DRUGSPEC nvarchar2(60) ,
	-- 剂型
	C_FIGURENAME nvarchar2(40) ,
	-- 生产厂家名称
	C_FACTORYNAME nvarchar2(100) ,
	-- 批次编号
	C_BATCHCD nvarchar2(100),
	-- 批次详细信息
	C_BATCHDETAIL nvarchar2(600),
	-- 药品包装单位编码
	C_DRUGPACKUNITCD varchar2(40) ,
	-- 药品包装单位名称
	C_DRUGPACKUNITNAME nvarchar2(40) ,
	-- 药品出库明细表
	C_DRUGPACKUNITPRICE number(12,4) ,
	-- 药品使用单位编码
	C_USEUNITCD nvarchar2(40) ,
	-- 药品使用单位名称
	C_USEUNITNAME nvarchar2(40),
	-- 药品使用单位单价
	N_USEUNITPRICE number(18,4),
	-- 药品领药单位编码
	C_SENDUNITCD nvarchar2(40) ,
	-- 药品领药单位名称
	C_SENDUNITNAME nvarchar2(40) ,
	-- 药品领药单位单价
	N_SENDUNITPRICE number(18,4) ,
	-- 药品数量(按领药单位）
	N_DRUGNUMBER number(10,2) ,
	-- 药品金额
	N_DRUGAMOUNT number(20,4) ,
	-- 药品用法编码
	C_DRUGUSAGECD nvarchar2(40) ,
	-- 药品用法名称
	C_DRUGUSAGENAME nvarchar2(80) ,
	-- 药品用次名称
	C_DRUGUSETIMESDAYNAME nvarchar2(100) ,
	-- 药品用次编码
	C_DRUGUSETIMESDAYCD nvarchar2(40) ,
	-- 医生编码
	C_DOCTORCD nvarchar2(36) ,
	-- 医生姓名
	C_DOCTORNAME nvarchar2(36) ,
	-- 医嘱嘱托
	C_DOCTORADVICE nvarchar2(100),
	-- 床位号
	C_BEDCD nvarchar2(40),
	-- 日次
	C_DAYTIME nvarchar2(40),
	-- 剂量
	C_DOSAGE nvarchar2(40),
	-- 区域
	area varchar2(128) ,
	-- 机构
	INSTITUTION varchar2(128) 
);


CREATE TABLE T_SIIP_SENDLIST
(
	-- 发药单流水号
	C_SENDLISTCD nvarchar2(60) ,
	-- 创建者编号
	CREATORCD nvarchar2(40) ,
	-- 创建者名称
	CREATORNAME nvarchar2(40) ,
	-- 创建时间
	CREATETIME date ,
	-- His发药单流水号
	C_SENDLISTCDHIS nvarchar2(40) ,
	-- 所属病区部门编码
	C_WARDCD nvarchar2(20) ,
	-- 所属病区部门名称
	C_WARDNAME nvarchar2(160) ,
	-- 单据处理状态 0:未处理 1:已处理 9:已删除
	N_DEELSTATUS number(2,0) ,
	-- 单据接口发送状态
	N_SENDSTATUS number(2,0) ,
	-- 处理药房编码
	C_STORECD nvarchar2(20) ,
	-- 处理药房名称
	C_STORENAME nvarchar2(160) ,
	-- 发药类型
	N_SENDTYPE number(1,0) ,
	-- 录入人编码
	C_ENTEROPERCD nvarchar2(40) ,
	-- 录入人姓名
	C_ENTEROPERNAME nvarchar2(40) ,
	-- 发药人编码
	C_UPTOPERCD nvarchar2(40),
	-- 发药人姓名
	C_UPTOPERNAME nvarchar2(160),
	-- 总金额
	N_AMOUNT number(12,4) ,
	-- 录入时间
	D_ENTERTIME date ,
	-- 存盘时间
	D_UPTDATETIME date,
	-- 发药类型名称
	C_SENDTYPENAME nvarchar2(40) ,
	-- 区域
	area varchar2(128) ,
	-- 机构
	INSTITUTION varchar2(128) 
);


CREATE TABLE T_SIIP_SENDLISTCOLLECT
(
	-- 汇总单序号
	N_COLLECTID nvarchar2(60) ,
	-- 创建者编号
	CREATORCD nvarchar2(40) ,
	-- 创建者名称
	CREATORNAME nvarchar2(40) ,
	-- 创建时间
	CREATETIME date ,
	-- 药品编号
	C_DRUGCD nvarchar2(60) ,
	-- 药品通用名称
	C_COMMONNAME nvarchar2(100) ,
	-- 药品商品名称
	C_TRADENAME nvarchar2(100) ,
	-- 药品规格
	C_DRUGSPEC nvarchar2(60) ,
	-- 剂型
	C_FIGURENAME nvarchar2(40) ,
	-- 生产厂家名称
	C_FACTORYNAME nvarchar2(100) ,
	-- 药房名称
	C_DRUGSTORENAME nvarchar2(160) ,
	-- 药房编号
	C_DRUGSTORECD nvarchar2(40) ,
	-- 单据处理状态 0:未处理 1:已处理 9:已删除
	N_DEELSTATUS number(2,0) ,
	-- 药品包装单位编码
	C_DRUGPACKUNITCD varchar2(36) ,
	-- 药品包装单位名称
	C_DRUGPACKUNITNAME nvarchar2(200) ,
	-- 药品包装单位单价
	C_DRUGPACKUNITPRICE number(12,4) ,
	-- 药品使用单位编码
	C_USEUNITCD nvarchar2(40) ,
	-- 药品使用单位名称
	C_USEUNITNAME nvarchar2(40) ,
	-- 药品使用单位单价
	N_USEUNITPRICE number(12,4) ,
	-- 药品领药单位编码
	C_SENDUNITCD nvarchar2(40) ,
	-- 药品领药单位名称
	C_SENDUNITNAME nvarchar2(40) ,
	-- 药品领药单位单价
	N_SENDUNITPRICE number(12,4) ,
	-- 药品数量(按领药单位）
	N_DRUGNUMBER number(10,2) ,
	-- 药品金额
	N_DRUGAMOUNT number(12,4) ,
	-- 包装合计
	C_PACKTOTAL nvarchar2(100),
	-- 实际库存
	C_REALSTOCK nvarchar2(100),
	-- 使用合计
	C_USETOTAL nvarchar2(100),
	-- 区域
	area varchar2(128) ,
	-- 机构
	INSTITUTION varchar2(128) 
);


CREATE TABLE T_SIIP_SENDLISTDETAIL
(
	-- 序号
	ID nvarchar2(60) ,
	-- 发药单流水号
	C_SENDLISTCD nvarchar2(60) ,
	-- 创建者编号
	CREATORCD nvarchar2(40) ,
	-- 创建者名称
	CREATORNAME nvarchar2(40) ,
	-- 创建时间
	CREATETIME date ,
	-- 病人ID号
	C_PATIENTID nvarchar2(100) ,
	-- 病人姓名
	C_PATIENTNAME nvarchar2(36) ,
	-- 病人姓名拼音码
	C_PATIENTNAMEPYCODE nvarchar2(36),
	-- 药品编号
	C_DRUGCD nvarchar2(60) ,
	-- 药品通用名称
	C_COMMONNAME nvarchar2(100) ,
	-- 药品商品名称
	C_TRADENAME nvarchar2(100) ,
	-- 药品规格
	C_DRUGSPEC nvarchar2(60) ,
	-- 剂型
	C_FIGURENAME nvarchar2(40) ,
	-- 生产厂家名称
	C_FACTORYNAME nvarchar2(100) ,
	-- 批次编号
	C_BATCHCD nvarchar2(100),
	-- 批次详细信息
	C_BATCHDETAIL nvarchar2(600),
	-- 药品包装单位编码
	C_DRUGPACKUNITCD varchar2(36) ,
	-- 药品包装单位名称
	C_DRUGPACKUNITNAME nvarchar2(200) ,
	-- 药品包装单位单价
	C_DRUGPACKUNITPRICE number(12,4) ,
	-- 药品使用单位编码
	C_USEUNITCD nvarchar2(40) ,
	-- 药品使用单位名称
	C_USEUNITNAME nvarchar2(40),
	-- 药品使用单位单价
	N_USEUNITPRICE number(12,4),
	-- 药品领药单位编码
	C_SENDUNITCD nvarchar2(40) ,
	-- 药品领药单位名称
	C_SENDUNITNAME nvarchar2(40) ,
	-- 药品领药单位单价
	N_SENDUNITPRICE number(12,4) ,
	-- 药品数量(按领药单位）
	N_DRUGNUMBER  number(12,2) ,
	-- 药品金额
	N_DRUGAMOUNT number(12,4) ,
	-- 药品用法编码
	C_DRUGUSAGECD nvarchar2(40) ,
	-- 药品用法名称
	C_DRUGUSAGENAME nvarchar2(80) ,
	-- 药品用次编码
	C_DRUGUSETIMESDAYCD nvarchar2(40) ,
	-- 药品用次名称
	C_DRUGUSETIMESDAYNAME nvarchar2(100) ,
	-- 医生编码
	C_DOCTORCD nvarchar2(36) ,
	-- 医生姓名
	C_DOCTORNAME nvarchar2(36) ,
	-- 医嘱嘱托
	C_DOCTORADVICE nvarchar2(100),
	-- 床位号
	C_BEDCD nvarchar2(40),
	-- 日次
	C_DAYTIME nvarchar2(40),
	-- 剂量
	C_DOSAGE nvarchar2(40),
	-- 区域
	area varchar2(128) ,
	-- 机构
	INSTITUTION varchar2(128) 
);

CREATE TABLE T_SIOP_RECIPE(
	--处方流水号
	C_RECIPECD	VARCHAR2(32) PRIMARY KEY NOT NULL ,
	--原处方号
	C_RECIPECDOLD		VARCHAR2(32),
	--处方有效期
	D_RECIPEEXPIREDATE		DATE,
	--处方类型
	C_RECIPETYPE		VARCHAR2(32),
	--处方种类
	N_RECIPESORT		NUMBER(1,0),
	--特殊处方标识
	N_SPECIALFLG		NUMBER(1,0),
	--处方剂数
	N_RECIPECOUNT		NUMBER(10,0),
	--单剂处方金额
	N_RECIPEAMOUNT		NUMBER	(12,4),
	--处方录入人编码
	C_RECIPEENTEROPER		NVARCHAR2	(20),
	--处方录入时间
	D_DOCTORDATETIME		DATE,
	--医生编码
	C_DOCTORCD		NVARCHAR2	(160),
	--医生姓名
	C_DOCTORNAME		NVARCHAR2	(400),
	--医生部门编码
	C_DOCTORDEPTCD		VARCHAR2	(10),
	--医生部门名称
	C_DOCTORDEPTNAME		NVARCHAR2	(40),
	--收费人编码
	C_FEEOPER		VARCHAR2	(20),
	--收费时间
	D_FEEDATETIME		DATE	,
	--全部处方收费金额
	N_FEEAMOUNT		NUMBER	(12,4),
	--主诊断编号
	C_PATIENTICD10CD		NVARCHAR2	(20),
	--主诊断名称
	C_PATIENTICD10NAME		NVARCHAR2	(100),
	--主诊断说明
	C_PATIENTICD10NOTES		NVARCHAR2	(510),
	--病人ID号/身份证号
	C_PATIENTID		VARCHAR2	(50),
	--就诊卡号
	C_PATIENTCARDCD		VARCHAR2	(50),
	--市民卡号
	C_CITYCARDCD		VARCHAR2	(50),
	--就诊次数
	C_PATIENTTIMES		NUMBER	(10,0),
	--HIS处方号
	C_RECIPECDHIS		VARCHAR2	(30),
	--结算序号
	N_LEDGERNO		NUMBER	(10,0),
	--姓名
	C_PATIENTNAME		NVARCHAR2	(40),
	--性别
	C_PATIENTSEX		NVARCHAR2	(4),
	--年龄
	C_PATIENTAGE		NVARCHAR2	(40),
	--联系方式
	C_PATIENTPHONE		NVARCHAR2	(60),
	--工作单位
	C_PATIENTWORKUNIT		NVARCHAR2	(100),
	--出生日期
	D_PATIENTBIRTHDAY		DATE,
	--身份类别编码
	C_PATIENTSORTCD		NVARCHAR2	(40),
	--身份类别名称
	C_PATIENTSORTNAME		NVARCHAR2	(40),
	--病人身高
	N_PATIENTHEIGHT		NUMBER	(3,0),
	--病人体重
	N_PATIENTWEIGHT		NUMBER	(3,0),
	--处方状态
	N_RECIPESTATUS		NUMBER	(1,0),
	--接口数据状态
	N_INTERFACESTATUS		NUMBER	(1,0),
	--VIP标记
	N_VIPFLG		NUMBER	(1,0),
	--医嘱
	C_DOCTORADVICE		NVARCHAR2	(510),
	--新增时间
	D_ADDDATETIME		DATE,
	--二维码
	B_TWOCODE		BLOB,
	--扩展字段1
	C_NOTESEX1		NVARCHAR2	(100),
	--扩展字段2
	C_NOTESEX2		NVARCHAR2	(100),
	--扩展字段3
	C_NOTESEX3		NVARCHAR2	(100),
	--扩展字段4
	C_NOTESEX4		NVARCHAR2	(100),
	--扩展字段5
	C_NOTESEX5		NVARCHAR2	(100),
	--门诊药房编码
	C_STORECD		NVARCHAR2	(10),
	--发药人编码
	C_UPTOPERCD		NVARCHAR2	(20),
	--发药人姓名
	C_UPTOPERNAME		NVARCHAR2	(20),
	--存盘时间
	D_UPTDATETIME		DATE,
	--调剂人编码
	C_ADJUSTCD		NVARCHAR2	(40),
	--调剂人姓名
	C_ADJUSTNAME		NVARCHAR2	(40),
	--发票流水号
	C_INVOICESERIALNUM		NVARCHAR2	(40),
	--存在输液明细
	N_INFUSIONRECIPEFLG		NUMBER	(1,0),
	--是否是急诊病人
	N_EMERGENCYPATIENTFLG		NUMBER	(1,0),
	--是否在院输液
	N_INFUSIONBRINGBACK		NUMBER	(1,0),
	--患者姓名拼音码
	C_PATIENTNAMEPYCODE		VARCHAR2	(20),
	--窗口号
	N_WINDOWNO		NUMBER(2,0)
);


CREATE TABLE T_SIOP_RECIPEDETAIL(
	C_RECIPECD	VARCHAR2	(30) PRIMARY KEY  NOT NULL ,
	C_RECIPECDOLD	VARCHAR2	(30),
	N_DRUGNO	NUMBER	(10,0),
	N_DRUGNOOLD	NUMBER	(10,0),
	C_DRUGCD	NVARCHAR2	(60),
	C_DRUGSERIALNO	VARCHAR2	(20),
	N_GROUPCD	NUMBER	(10,0),
	N_GROUPSERIALNO	NUMBER	(10,0),
	C_DRUGNAME	NVARCHAR2	(200),
	C_DRUGSPEC	NVARCHAR2	(80),
	C_DRUGFIGURECD	VARCHAR2	(20),
	C_DRUGFIGURENAME	NVARCHAR2	(40),
	C_DRUGUSAGECD	VARCHAR2	(20),
	C_DRUGUSAGENAME	NVARCHAR2	(40),
	C_DRUGUSETIMESDAYCD	VARCHAR2	(20),
	C_DRUGUSETIMESDAYNAME	NVARCHAR2	(40),
	C_DRUGVEINTYPE	NVARCHAR2	(40),
	N_DRUGVEINHIGH	NUMBER	(10,0),
	N_DRUGVEINLOWER	NUMBER	(10,0),
	N_DRUGUSEDAYS	NUMBER	(10,0),
	N_DRUGUSEDOSE	NUMBER	(12,4),
	C_DRUGDOSEUNIT	NVARCHAR2	(40),
	N_DRUGSKINTEST	NUMBER	(2,0),
	N_REPORTDRUG	NUMBER	(1,0),
	N_DRUGPRICE	NUMBER	(12,4),
	N_DRUGNUMBER	NUMBER	(12,2),
	C_DRUGOUTUNIT	VARCHAR2	(6),
	N_DRUGAMOUNT	NUMBER	(12,4),
	C_NOTES	NVARCHAR2	(510),
	N_DRUGVEINSORT	NUMBER	(1,0),
	N_ISUSEDAGAIN	NUMBER	(1,0),
	D_ADDDATETIME	DATE	,
	C_NOTESEX1	NVARCHAR2	(100),
	C_NOTESEX2	NVARCHAR2	(100),
	C_NOTESEX3	NVARCHAR2	(100),
	C_NOTESEX4	NVARCHAR2	(100),
	C_NOTESEX5	NVARCHAR2	(100),
	N_USENUMBERBYTURN	NUMBER	(5,0),
	N_PRICEBUY	NUMBER	(12,4),
	N_INFUSIONFLG	NUMBER	(1,0),
	N_DRUGBACKFLG	NUMBER	(1,0),
	N_HIGHRISKFLG	NUMBER	(1,0),
	C_DRUGOUTUNITCD	NVARCHAR2	(40),
	C_FACTORYNAME	NVARCHAR2	(200),
	C_BATCHCD	NVARCHAR2	(100),
	C_BATCHDETAIL	NVARCHAR2	(300),
	AREA VARCHAR2(128),
	INSTITUTION VARCHAR2(128)
);


CREATE TABLE T_SIIP_SURPLUS(
		ID VARCHAR2(32) PRIMARY KEY NOT NULL,
		DRUGNAME VARCHAR2(255),
		N_DRUGAMOUNT	NUMBER	(12,4),
		SURPLUS DATE,
		INSTITUTION VARCHAR2(128),
		N_DRUGCOUNT NUMBER	(12,2)
);

CREATE TABLE T_SIOP_ELECCODECIRCULATE (
	ID               NVARCHAR2(60) PRIMARY KEY NOT NULL ,
	C_ELECTRONICCODE NVARCHAR2(60),
	C_BILLCD         NVARCHAR2(60),
	N_TYPE           CHAR(2),
	D_ADDDATETIME    DATE,
	N_STATUS         CHAR(1),
	N_DRUGNAME       VARCHAR2(200),
	MANUFACTURE      VARCHAR2(200),
	N_DRUGTYPE       VARCHAR2(32)
);

/* Comments */

COMMENT ON COLUMN T_SIIP_DRUGINSTORE.C_ACCEPTBILLCD IS '入库单号';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.CREATORCD IS '创建者编号';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.CREATORNAME IS '创建者名称';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.CREATETIME IS '创建时间';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.C_OUTSTOREBILLUPCD IS '相关单号';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.D_ACCEPTDATETIME IS '入库时间';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.C_ACCEPTTYPE IS '入库类型';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.N_DEELSTATUS IS '单据处理状态 0:未处理 1:已处理 9:已删除';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.N_SENDSTATUS IS '单据接口发送状态 0：未发送  1：已发送';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.C_SENDDEPTCD IS '相关部门编码';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.C_OUTSTORENAME IS '相关部门名称';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.C_ACCEPTDEPTCD IS '入库药房编码';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.C_INSTORENAME IS '入库药房名称';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.N_ACCEPTCOUNT IS '入库品种数';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.N_DRUGAMOUNT IS '药品总金额';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.C_ACCEPTOPERCD IS '入库操作员编码';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.C_UPTOPERCD IS '修改操作员编码';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.D_UPTDATETIME IS '更新时间';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.C_ACCEPTOPERNAME IS '入库操作员名称';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.C_UPTOPERNAME IS '修改操作员名称';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.C_REMARK IS '备注';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.C_AUDITORNAME IS '审核人姓名';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.C_SHELFUPPEOPLE IS '上架人姓名';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.INSTITUTION IS '机构';
COMMENT ON COLUMN T_SIIP_DRUGINSTORE.area IS '区域';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.ID IS '序号';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.CREATORCD IS '创建者编号';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.CREATORNAME IS '创建者名称';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.CREATETIME IS '创建时间';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.C_ACCEPTBILLCD IS '入库单号';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.C_DRUGCD IS '药品编号';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.C_TRADENAME IS '药品商品名称';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.C_COMMONNAME IS '药品通用名称';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.C_FACTORYNAME IS '生产厂家名称';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.C_DRUGSPEC IS '药品规格';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.C_FIGURENAME IS '剂型';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.C_BATCHCD IS '批次编号';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.C_BATCHDETAIL IS '批次详细信息';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.C_POSITIONCD IS '货位储存号';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.C_PACKUNITCD IS '药品包装单位编码';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.C_PACKUNITNAME IS '药品包装单位名称';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.N_PACKUNITPRICE IS '药品出库明细表';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.N_USEUNITPRICE IS '药品使用单位单价';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.C_USEUNITCD IS '药品使用单位编码';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.C_USEUNITNAME IS '药品使用单位名称';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.C_INSTOREUNITCD IS '药品入库单位编码';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.C_INSTOREUNITNAME IS '药品入库单位名称';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.N_INSTOREUNITPRICE IS '药品入库单位单价';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.N_DRUGCOUNT IS '药品入库数量';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.N_DRUGAMOUNT IS '药品入库金额';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.D_UPTDATETIME IS '更新时间';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.INSTITUTION IS '机构';
COMMENT ON COLUMN T_SIIP_DRUGINSTOREDETAIL.area IS '区域';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.C_OUTBILLCD IS '出库单号';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.CREATORCD IS '创建者编号';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.CREATORNAME IS '创建者名称';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.CREATETIME IS '创建时间';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.C_INSTOREBILLUPCD IS '相关单号';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.D_OUTDATETIME IS '出库时间';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.C_OUTTYPE IS '出库类型';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.N_DEELSTATUS IS '单据处理状态 0:未处理 1:已处理 9:已删除';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.N_SENDSTATUS IS '单据接口发送状态';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.C_ACCEPTDEPTCD IS '相关库房编码';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.C_ACCEPTDEPTNAME IS '相关库房名称';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.C_OUTDEPTCD IS '出库药房编码';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.C_OUTDEPTNAME IS '出库药房名称';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.N_OUTCOUNT IS '出库品种数';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.N_DRUGAMOUNT IS '药品总金额';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.C_OUTOPERCD IS '出库操作员编码';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.C_ACCEPTOPERCD IS '相关操作员编码';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.C_UPTOPERCD IS '修改操作员编码';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.D_UPTDATETIME IS '更新时间';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.C_OUTOPERNAME IS '出库操作员名称';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.C_ACCEPTOPERNAME IS '相关操作员名称';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.C_UPTOPERNAME IS '修改操作员名称';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.C_REMARK IS '备注';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.C_AUDITORNAME IS '审核人姓名';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.C_SHELFDOWNPEOPLE IS '下架人姓名';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.INSTITUTION IS '机构';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTORE.area IS '区域';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.ID IS '序号';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.C_OUTBILLCD IS '出库单号';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.CREATORCD IS '创建者编号';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.CREATORNAME IS '创建者名称';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.CREATETIME IS '创建时间';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.C_DRUGCD IS '药品编号';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.C_TRADENAME IS '药品商品名称';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.C_COMMONNAME IS '药品通用名称';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.C_FACTORYNAME IS '生产厂家名称';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.C_DRUGSPEC IS '药品规格';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.C_FIGURENAME IS '剂型';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.C_BATCHCD IS '批次编号';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.C_BATCHDETAIL IS '批次详细信息';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.C_POSITIONCD IS '货位储存号';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.C_PACKUNITCD IS '药品包装单位编码';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.C_PACKUNITNAME IS '药品包装单位名称';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.N_PACKUNITPRICE IS '药品出库明细表';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.C_USEUNITCD IS '药品使用单位编码';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.C_USEUNITNAME IS '药品使用单位名称';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.N_USEUNITPRICE IS '药品使用单位单价';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.C_OUTSTORECD IS '药品出库单位编码';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.C_OUTSTORENAME IS '药品出库单位名称';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.N_OUTSTOREPRICE IS '药品出库单位单价';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.N_DRUGCOUNT IS '药品出库数量';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.N_DRUGAMOUNT IS '药品出库金额';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.D_UPTDATETIME IS '更新时间';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.INSTITUTION IS '机构';
COMMENT ON COLUMN T_SIIP_DRUGOUTSTOREDETAIL.area IS '区域';
COMMENT ON COLUMN T_SIIP_DRUGSTORAGESTOCK.ID IS '序号';
COMMENT ON COLUMN T_SIIP_DRUGSTORAGESTOCK.C_DRUGCD IS '药品编号';
COMMENT ON COLUMN T_SIIP_DRUGSTORAGESTOCK.C_DRUGUNITCD IS '入库单位编码';
COMMENT ON COLUMN T_SIIP_DRUGSTORAGESTOCK.C_BATCHCD IS '批次编号';
COMMENT ON COLUMN T_SIIP_DRUGSTORAGESTOCK.CREATORCD IS '创建者编号';
COMMENT ON COLUMN T_SIIP_DRUGSTORAGESTOCK.CREATORNAME IS '创建者名称';
COMMENT ON COLUMN T_SIIP_DRUGSTORAGESTOCK.CREATETIME IS '创建时间';
COMMENT ON COLUMN T_SIIP_DRUGSTORAGESTOCK.D_NUMBER IS '部门编码';
COMMENT ON COLUMN T_SIIP_DRUGSTORAGESTOCK.N_DRUGSTOCK IS '库存量';
COMMENT ON COLUMN T_SIIP_DRUGSTORAGESTOCK.INSTITUTION IS '机构';
COMMENT ON COLUMN T_SIIP_DRUGSTORAGESTOCK.area IS '区域';
COMMENT ON COLUMN T_SIIP_INVDRUGSTORE.C_INVSTORECD IS '盘点编号';
COMMENT ON COLUMN T_SIIP_INVDRUGSTORE.CREATORCD IS '创建者编号';
COMMENT ON COLUMN T_SIIP_INVDRUGSTORE.CREATORNAME IS '创建者名称';
COMMENT ON COLUMN T_SIIP_INVDRUGSTORE.CREATETIME IS '创建时间';
COMMENT ON COLUMN T_SIIP_INVDRUGSTORE.C_DRUGSTORECD IS '药房编号';
COMMENT ON COLUMN T_SIIP_INVDRUGSTORE.C_DRUGSTORENAME IS '药房名称';
COMMENT ON COLUMN T_SIIP_INVDRUGSTORE.N_DEELSTATUS IS '单据处理状态 0:未处理 1:已处理 9:已删除';
COMMENT ON COLUMN T_SIIP_INVDRUGSTORE.N_SENDSTATUS IS '单据接口发送状态 0：未发送  1：已发送';
COMMENT ON COLUMN T_SIIP_INVDRUGSTORE.D_INVSTORETIME IS '盘存时间';
COMMENT ON COLUMN T_SIIP_INVDRUGSTORE.N_BEFOREINVAMOUT IS '盘点前总金额';
COMMENT ON COLUMN T_SIIP_INVDRUGSTORE.N_AFTERINVAMOUNT IS '盘点后总金额';
COMMENT ON COLUMN T_SIIP_INVDRUGSTORE.D_UPTDATETIME IS '更新时间';
COMMENT ON COLUMN T_SIIP_INVDRUGSTORE.C_AUDITORNAME IS '审核人姓名';
COMMENT ON COLUMN T_SIIP_INVDRUGSTORE.C_INVPERSONNAME IS '盘点人';
COMMENT ON COLUMN T_SIIP_INVDRUGSTORE.N_DRUGSCOUNT IS '药品品种数';
COMMENT ON COLUMN T_SIIP_INVDRUGSTORE.area IS '区域';
COMMENT ON COLUMN T_SIIP_INVDRUGSTORE.INSTITUTION IS '机构';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.ID IS '序号';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.C_INVSTORECD IS '盘点编号';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.CREATORCD IS '创建者编号';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.CREATORNAME IS '创建者名称';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.CREATETIME IS '创建时间';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.C_DRUGCD IS '药品编号';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.C_TRADENAME IS '药品商品名称';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.C_COMMONNAME IS '药品通用名称';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.C_DRUGSPEC IS '药品规格';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.C_FIGURENAME IS '剂型';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.C_FACTORYNAME IS '生产厂家名称';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.C_POSITIONCD IS '货位储存号';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.D_UPTDATETIME IS '更新时间';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.C_DRUGINVUNITCD IS '药品盘点单位编码';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.C_DRUGINVUNITNAME IS '药品盘点单位名称';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.N_OLDSTOCK IS '盘点前库存量';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.N_REALSTOCK IS '盘点后库存量';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.N_OLDAMOUNT IS '盘点前总金额';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.N_REALAMOUNT IS '盘点后总金额';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.C_PACKUNITCD IS '药品包装单位编码';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.C_PACKUNITNAME IS '药品包装单位名称';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.C_USEUNITCD IS '药品使用单位编码';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.C_USEUNITNAME IS '药品使用单位名称';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.N_PACKUNITPRICE IS '药品出库明细表';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.N_USEUNITPRICE IS '药品使用单位单价';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.N_INVUNITPRICE IS '药品盘点单位单价';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.N_DRUGPACKMODULUS IS '到包装单位转换系数';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.area IS '区域';
COMMENT ON COLUMN T_SIIP_INVDRUGSTOREDETAIL.INSTITUTION IS '机构';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.ID IS '序号';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.N_COLLECTID IS '汇总单序号';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_SENDLISTCD IS '发药单流水号';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.CREATORCD IS '创建者编号';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.CREATORNAME IS '创建者名称';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.CREATETIME IS '创建时间';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_PATIENTID IS '病人ID号';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_PATIENTNAME IS '病人姓名';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_PATIENTNAMEPYCODE IS '病人姓名拼音码';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_DRUGCD IS '药品编号';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_COMMONNAME IS '药品通用名称';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_TRADENAME IS '药品商品名称';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_DRUGSPEC IS '药品规格';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_FIGURENAME IS '剂型';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_FACTORYNAME IS '生产厂家名称';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_BATCHCD IS '批次编号';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_BATCHDETAIL IS '批次详细信息';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_DRUGPACKUNITCD IS '药品包装单位编码';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_DRUGPACKUNITNAME IS '药品包装单位名称';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_DRUGPACKUNITPRICE IS '药品出库明细表';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_USEUNITCD IS '药品使用单位编码';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_USEUNITNAME IS '药品使用单位名称';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.N_USEUNITPRICE IS '药品使用单位单价';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_SENDUNITCD IS '药品领药单位编码';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_SENDUNITNAME IS '药品领药单位名称';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.N_SENDUNITPRICE IS '药品领药单位单价';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.N_DRUGNUMBER IS '药品数量(按领药单位）';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.N_DRUGAMOUNT IS '药品金额';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_DRUGUSAGECD IS '药品用法编码';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_DRUGUSAGENAME IS '药品用法名称';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_DRUGUSETIMESDAYNAME IS '药品用次名称';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_DRUGUSETIMESDAYCD IS '药品用次编码';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_DOCTORCD IS '医生编码';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_DOCTORNAME IS '医生姓名';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_DOCTORADVICE IS '医嘱嘱托';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_BEDCD IS '床位号';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_DAYTIME IS '日次';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.C_DOSAGE IS '剂量';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.area IS '区域';
COMMENT ON COLUMN T_SIIP_SENDCOLLECTDETAIL.INSTITUTION IS '机构';
COMMENT ON COLUMN T_SIIP_SENDLIST.C_SENDLISTCD IS '发药单流水号';
COMMENT ON COLUMN T_SIIP_SENDLIST.CREATORCD IS '创建者编号';
COMMENT ON COLUMN T_SIIP_SENDLIST.CREATORNAME IS '创建者名称';
COMMENT ON COLUMN T_SIIP_SENDLIST.CREATETIME IS '创建时间';
COMMENT ON COLUMN T_SIIP_SENDLIST.C_SENDLISTCDHIS IS 'His发药单流水号';
COMMENT ON COLUMN T_SIIP_SENDLIST.C_WARDCD IS '所属病区部门编码';
COMMENT ON COLUMN T_SIIP_SENDLIST.C_WARDNAME IS '所属病区部门名称';
COMMENT ON COLUMN T_SIIP_SENDLIST.N_DEELSTATUS IS '单据处理状态 0:未处理 1:已处理 9:已删除';
COMMENT ON COLUMN T_SIIP_SENDLIST.N_SENDSTATUS IS '单据接口发送状态';
COMMENT ON COLUMN T_SIIP_SENDLIST.C_STORECD IS '处理药房编码';
COMMENT ON COLUMN T_SIIP_SENDLIST.C_STORENAME IS '处理药房名称';
COMMENT ON COLUMN T_SIIP_SENDLIST.N_SENDTYPE IS '发药类型';
COMMENT ON COLUMN T_SIIP_SENDLIST.C_ENTEROPERCD IS '录入人编码';
COMMENT ON COLUMN T_SIIP_SENDLIST.C_ENTEROPERNAME IS '录入人姓名';
COMMENT ON COLUMN T_SIIP_SENDLIST.C_UPTOPERCD IS '发药人编码';
COMMENT ON COLUMN T_SIIP_SENDLIST.C_UPTOPERNAME IS '发药人姓名';
COMMENT ON COLUMN T_SIIP_SENDLIST.N_AMOUNT IS '总金额';
COMMENT ON COLUMN T_SIIP_SENDLIST.D_ENTERTIME IS '录入时间';
COMMENT ON COLUMN T_SIIP_SENDLIST.D_UPTDATETIME IS '存盘时间';
COMMENT ON COLUMN T_SIIP_SENDLIST.C_SENDTYPENAME IS '发药类型名称';
COMMENT ON COLUMN T_SIIP_SENDLIST.area IS '区域';
COMMENT ON COLUMN T_SIIP_SENDLIST.INSTITUTION IS '机构';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.N_COLLECTID IS '汇总单序号';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.CREATORCD IS '创建者编号';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.CREATORNAME IS '创建者名称';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.CREATETIME IS '创建时间';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.C_DRUGCD IS '药品编号';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.C_COMMONNAME IS '药品通用名称';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.C_TRADENAME IS '药品商品名称';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.C_DRUGSPEC IS '药品规格';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.C_FIGURENAME IS '剂型';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.C_FACTORYNAME IS '生产厂家名称';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.C_DRUGSTORENAME IS '药房名称';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.C_DRUGSTORECD IS '药房编号';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.N_DEELSTATUS IS '单据处理状态 0:未处理 1:已处理 9:已删除';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.C_DRUGPACKUNITCD IS '药品包装单位编码';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.C_DRUGPACKUNITNAME IS '药品包装单位名称';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.C_DRUGPACKUNITPRICE IS '药品包装单位单价';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.C_USEUNITCD IS '药品使用单位编码';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.C_USEUNITNAME IS '药品使用单位名称';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.N_USEUNITPRICE IS '药品使用单位单价';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.C_SENDUNITCD IS '药品领药单位编码';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.C_SENDUNITNAME IS '药品领药单位名称';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.N_SENDUNITPRICE IS '药品领药单位单价';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.N_DRUGNUMBER IS '药品数量(按领药单位）';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.N_DRUGAMOUNT IS '药品金额';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.C_PACKTOTAL IS '包装合计';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.C_REALSTOCK IS '实际库存';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.C_USETOTAL IS '使用合计';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.area IS '区域';
COMMENT ON COLUMN T_SIIP_SENDLISTCOLLECT.INSTITUTION IS '机构';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.ID IS '序号';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_SENDLISTCD IS '发药单流水号';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.CREATORCD IS '创建者编号';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.CREATORNAME IS '创建者名称';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.CREATETIME IS '创建时间';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_PATIENTID IS '病人ID号';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_PATIENTNAME IS '病人姓名';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_PATIENTNAMEPYCODE IS '病人姓名拼音码';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_DRUGCD IS '药品编号';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_COMMONNAME IS '药品通用名称';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_TRADENAME IS '药品商品名称';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_DRUGSPEC IS '药品规格';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_FIGURENAME IS '剂型';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_FACTORYNAME IS '生产厂家名称';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_BATCHCD IS '批次编号';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_BATCHDETAIL IS '批次详细信息';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_DRUGPACKUNITCD IS '药品包装单位编码';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_DRUGPACKUNITNAME IS '药品包装单位名称';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_DRUGPACKUNITPRICE IS '药品包装单位单价';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_USEUNITCD IS '药品使用单位编码';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_USEUNITNAME IS '药品使用单位名称';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.N_USEUNITPRICE IS '药品使用单位单价';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_SENDUNITCD IS '药品领药单位编码';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_SENDUNITNAME IS '药品领药单位名称';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.N_SENDUNITPRICE IS '药品领药单位单价';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.N_DRUGNUMBER  IS '药品数量(按领药单位）';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.N_DRUGAMOUNT IS '药品金额';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_DRUGUSAGECD IS '药品用法编码';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_DRUGUSAGENAME IS '药品用法名称';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_DRUGUSETIMESDAYCD IS '药品用次编码';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_DRUGUSETIMESDAYNAME IS '药品用次名称';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_DOCTORCD IS '医生编码';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_DOCTORNAME IS '医生姓名';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_DOCTORADVICE IS '医嘱嘱托';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_BEDCD IS '床位号';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_DAYTIME IS '日次';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.C_DOSAGE IS '剂量';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.area IS '区域';
COMMENT ON COLUMN T_SIIP_SENDLISTDETAIL.INSTITUTION IS '机构';
COMMENT ON COLUMN T_SIIP_RECIPE.AREA IS '区域';
COMMENT ON COLUMN T_SIIP_RECIPE.C_RECIPECD IS '处方流水号';
COMMENT ON COLUMN T_SIIP_RECIPE.C_RECIPECDOLD  IS '原处方号';
COMMENT ON COLUMN T_SIIP_RECIPE.D_RECIPEEXPIREDATE IS '处方有效期';
COMMENT ON COLUMN T_SIIP_RECIPE.C_RECIPETYPE IS '处方类型';
COMMENT ON COLUMN T_SIIP_RECIPE.N_RECIPESORT IS '处方种类';
COMMENT ON COLUMN T_SIIP_RECIPE.N_SPECIALFLG IS '特殊处方标识';
COMMENT ON COLUMN T_SIIP_RECIPE.N_RECIPECOUNT IS '处方剂数';
COMMENT ON COLUMN T_SIIP_RECIPE.N_RECIPEAMOUNT IS '单剂处方金额';
COMMENT ON COLUMN T_SIIP_RECIPE.C_RECIPEENTEROPER IS '处方录入人编码';
COMMENT ON COLUMN T_SIIP_RECIPE.D_DOCTORDATETIME IS '处方录入时间';
COMMENT ON COLUMN T_SIIP_RECIPE.C_DOCTORCD IS '医生编码';
COMMENT ON COLUMN T_SIIP_RECIPE.C_DOCTORNAME IS '医生姓名';
COMMENT ON COLUMN T_SIIP_RECIPE.C_DOCTORDEPTCD IS '医生部门编码';
COMMENT ON COLUMN T_SIIP_RECIPE.C_DOCTORDEPTNAME IS '医生部门名称';
COMMENT ON COLUMN T_SIIP_RECIPE.C_FEEOPER IS '收费人编码';
COMMENT ON COLUMN T_SIIP_RECIPE.D_FEEDATETIME IS '收费时间';
COMMENT ON COLUMN T_SIIP_RECIPE.N_FEEAMOUNT IS '全部处方收费金额';
COMMENT ON COLUMN T_SIIP_RECIPE.C_PATIENTICD10CD IS '主诊断编号';
COMMENT ON COLUMN T_SIIP_RECIPE.C_PATIENTICD10NAME IS '主诊断名称';
COMMENT ON COLUMN T_SIIP_RECIPE.C_PATIENTICD10NOTES IS '主诊断说明';
COMMENT ON COLUMN T_SIIP_RECIPE.C_PATIENTID IS '病人ID号/身份证号';
COMMENT ON COLUMN T_SIIP_RECIPE.C_PATIENTCARDCD IS '就诊卡号';
COMMENT ON COLUMN T_SIIP_RECIPE.C_CITYCARDCD IS '市民卡号';
COMMENT ON COLUMN T_SIIP_RECIPE.C_PATIENTTIMES IS '就诊次数';
COMMENT ON COLUMN T_SIIP_RECIPE.C_RECIPECDHIS IS 'HIS处方号';
COMMENT ON COLUMN T_SIIP_RECIPE.N_LEDGERNO IS '结算序号';
COMMENT ON COLUMN T_SIIP_RECIPE.C_PATIENTNAME IS '姓名';
COMMENT ON COLUMN T_SIIP_RECIPE.C_PATIENTSEX IS '性别';
COMMENT ON COLUMN T_SIIP_RECIPE.C_PATIENTAGE IS '年龄';
COMMENT ON COLUMN T_SIIP_RECIPE.C_PATIENTPHONE IS '联系方式';
COMMENT ON COLUMN T_SIIP_RECIPE.C_PATIENTWORKUNIT IS '工作单位';
COMMENT ON COLUMN T_SIIP_RECIPE.D_PATIENTBIRTHDAY IS '出生日期';
COMMENT ON COLUMN T_SIIP_RECIPE.C_PATIENTSORTCD IS '身份类别编码';
COMMENT ON COLUMN T_SIIP_RECIPE.C_PATIENTSORTNAME IS '身份类别名称';
COMMENT ON COLUMN T_SIIP_RECIPE.N_PATIENTHEIGHT IS '病人身高';
COMMENT ON COLUMN T_SIIP_RECIPE.N_PATIENTWEIGHT IS '病人体重';
COMMENT ON COLUMN T_SIIP_RECIPE.N_RECIPESTATUS IS '处方状态';
COMMENT ON COLUMN T_SIIP_RECIPE.N_INTERFACESTATUS IS '接口数据状态';
COMMENT ON COLUMN T_SIIP_RECIPE.N_VIPFLG IS 'VIP标记';
COMMENT ON COLUMN T_SIIP_RECIPE.C_DOCTORADVICE IS '医嘱';
COMMENT ON COLUMN T_SIIP_RECIPE.D_ADDDATETIME IS '新增时间';
COMMENT ON COLUMN T_SIIP_RECIPE.B_TWOCODE IS '二维码';
COMMENT ON COLUMN T_SIIP_RECIPE.C_NOTESEX1 IS '扩展字段1';
COMMENT ON COLUMN T_SIIP_RECIPE.C_NOTESEX2 IS '扩展字段2';
COMMENT ON COLUMN T_SIIP_RECIPE.C_NOTESEX3 IS '扩展字段3';
COMMENT ON COLUMN T_SIIP_RECIPE.C_NOTESEX4 IS '扩展字段4';
COMMENT ON COLUMN T_SIIP_RECIPE.C_NOTESEX5 IS '扩展字段5';
COMMENT ON COLUMN T_SIIP_RECIPE.C_STORECD IS '门诊药房编码';
COMMENT ON COLUMN T_SIIP_RECIPE.C_UPTOPERCD IS '发药人编码';
COMMENT ON COLUMN T_SIIP_RECIPE.C_UPTOPERNAME IS '发药人姓名';
COMMENT ON COLUMN T_SIIP_RECIPE.D_UPTDATETIME IS '存盘时间';
COMMENT ON COLUMN T_SIIP_RECIPE.C_ADJUSTCD IS '调剂人编码';
COMMENT ON COLUMN T_SIIP_RECIPE.C_ADJUSTNAME IS '调剂人姓名';
COMMENT ON COLUMN T_SIIP_RECIPE.C_INVOICESERIALNUM IS '发票流水号';
COMMENT ON COLUMN T_SIIP_RECIPE.N_INFUSIONRECIPEFLG IS '存在输液明细';
COMMENT ON COLUMN T_SIIP_RECIPE.N_EMERGENCYPATIENTFLG IS '是否是急诊病人';
COMMENT ON COLUMN T_SIIP_RECIPE.N_INFUSIONBRINGBACK IS '是否在院输液';
COMMENT ON COLUMN T_SIIP_RECIPE.C_PATIENTNAMEPYCODE IS '患者姓名拼音码';
COMMENT ON COLUMN T_SIIP_RECIPE.N_WINDOWNO IS '窗口号';