package com.simlink.task.entity;

// Generated 2016-10-3 9:10:20 by Hibernate Tools 3.2.2.GA
import javax.xml.bind.annotation.XmlRootElement;  
import javax.xml.bind.annotation.XmlAccessType;  
import javax.xml.bind.annotation.XmlAccessorType;  
import javax.xml.bind.annotation.XmlElement;  
import javax.xml.bind.annotation.XmlElementWrapper;  
import javax.xml.bind.annotation.XmlRootElement;  
import javax.xml.bind.annotation.XmlType; 
import javax.xml.bind.annotation.XmlTransient;  

import java.util.Date;

/**
 * TSiipDruginstoreId generated by hbm2java
 */
@SuppressWarnings({ "restriction", "unused", "serial" })
@XmlRootElement(name = "row")  
public class TSiipDruginstore implements java.io.Serializable {

	
	@XmlElement(name = "C_ACCEPTBILLCD") 
	private String CAcceptbillcd;
	
	@XmlElement(name = "CREATORCD")
	private String creatorcd;
	
	@XmlElement(name = "CREATORNAME")
	private String creatorname;
	
	@XmlElement(name = "CREATETIME")
	private Date createtime;
	
	@XmlElement(name = "C_OUTSTOREBILLUPCD")
	private String COutstorebillupcd;
	
	@XmlElement(name = "D_ACCEPTDATETIME")
	private Date DAcceptdatetime;
	
	@XmlElement(name = "C_ACCEPTTYPE")
	private String CAccepttype;
	
	@XmlElement(name = "N_DEELSTATUS")
	private Integer NDeelstatus;
	
	@XmlElement(name = "N_SENDSTATUS")
	private Integer NSendstatus;
	
	@XmlElement(name = "C_SENDDEPTCD")
	private String CSenddeptcd;
	
	@XmlElement(name = "C_OUTSTORENAME")
	private String COutstorename;
	
	@XmlElement(name = "C_ACCEPTDEPTCD")
	private String CAcceptdeptcd;
	
	@XmlElement(name = "C_INSTORENAME")
	private String CInstorename;
	
	@XmlElement(name = "N_ACCEPTCOUNT")
	private int NAcceptcount;
	
	@XmlElement(name = "N_DRUGAMOUNT")
	private Double NDrugamount;
	
	@XmlElement(name = "C_ACCEPTOPERCD")
	private String CAcceptopercd;
	
	@XmlElement(name = "C_UPTOPERCD")
	private String CUptopercd;
	
	@XmlElement(name = "D_UPTDATETIME")
	private Date DUptdatetime;
	
	@XmlElement(name = "C_ACCEPTOPERNAME")
	private String CAcceptopername;
	
	@XmlElement(name = "C_UPTOPERNAME")
	private String CUptopername;
	
	@XmlElement(name = "C_REMARK")
	private String CRemark;
	
	@XmlElement(name = "C_AUDITORNAME")
	private String CAuditorname;
	
	@XmlElement(name = "C_SHELFUPPEOPLE")
	private String CShelfuppeople;
	
	@XmlElement(name = "institution")
	private String institution;
	
	@XmlElement(name = "area")
	private String area;
	

	public TSiipDruginstore() {
		super();
	}

	public TSiipDruginstore(String CAcceptbillcd,
			String creatorcd, String creatorname, Date createtime,
			String COutstorebillupcd, Date DAcceptdatetime,
			String CAccepttype, Integer NDeelstatus, Integer NSendstatus,
			String CSenddeptcd, String COutstorename,
			String CAcceptdeptcd, String CInstorename,
			int NAcceptcount, Double NDrugamount, String institution,
			String area) {
		this.CAcceptbillcd = CAcceptbillcd;
		this.creatorcd = creatorcd;
		this.creatorname = creatorname;
		this.createtime = createtime;
		this.COutstorebillupcd = COutstorebillupcd;
		this.DAcceptdatetime = DAcceptdatetime;
		this.CAccepttype = CAccepttype;
		this.NDeelstatus = NDeelstatus;
		this.NSendstatus = NSendstatus;
		this.CSenddeptcd = CSenddeptcd;
		this.COutstorename = COutstorename;
		this.CAcceptdeptcd = CAcceptdeptcd;
		this.CInstorename = CInstorename;
		this.NAcceptcount = NAcceptcount;
		this.NDrugamount = NDrugamount;
		this.institution = institution;
		this.area = area;
	}

	public TSiipDruginstore(String CAcceptbillcd,
			String creatorcd, String creatorname, Date createtime,
			String COutstorebillupcd, Date DAcceptdatetime,
			String CAccepttype, Integer NDeelstatus, Integer NSendstatus,
			String CSenddeptcd, String COutstorename,
			String CAcceptdeptcd, String CInstorename,
			int NAcceptcount, Double NDrugamount,
			String CAcceptopercd, String CUptopercd,
			Date DUptdatetime, String CAcceptopername,
			String CUptopername, String CRemark,
			String CAuditorname, String CShelfuppeople,
			String institution, String area) {
		this.CAcceptbillcd = CAcceptbillcd;
		this.creatorcd = creatorcd;
		this.creatorname = creatorname;
		this.createtime = createtime;
		this.COutstorebillupcd = COutstorebillupcd;
		this.DAcceptdatetime = DAcceptdatetime;
		this.CAccepttype = CAccepttype;
		this.NDeelstatus = NDeelstatus;
		this.NSendstatus = NSendstatus;
		this.CSenddeptcd = CSenddeptcd;
		this.COutstorename = COutstorename;
		this.CAcceptdeptcd = CAcceptdeptcd;
		this.CInstorename = CInstorename;
		this.NAcceptcount = NAcceptcount;
		this.NDrugamount = NDrugamount;
		this.CAcceptopercd = CAcceptopercd;
		this.CUptopercd = CUptopercd;
		this.DUptdatetime = DUptdatetime;
		this.CAcceptopername = CAcceptopername;
		this.CUptopername = CUptopername;
		this.CRemark = CRemark;
		this.CAuditorname = CAuditorname;
		this.CShelfuppeople = CShelfuppeople;
		this.institution = institution;
		this.area = area;
	}

	@XmlTransient
	public String getCAcceptbillcd() {
		return this.CAcceptbillcd;
	}

	public void setCAcceptbillcd(String CAcceptbillcd) {
		this.CAcceptbillcd = CAcceptbillcd;
	}
	
	@XmlTransient
	public String getCreatorcd() {
		return this.creatorcd;
	}

	public void setCreatorcd(String creatorcd) {
		this.creatorcd = creatorcd;
	}
	@XmlTransient
	public String getCreatorname() {
		return this.creatorname;
	}

	public void setCreatorname(String creatorname) {
		this.creatorname = creatorname;
	}
	@XmlTransient
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}
	@XmlTransient
	public String getCOutstorebillupcd() {
		return this.COutstorebillupcd;
	}

	public void setCOutstorebillupcd(String COutstorebillupcd) {
		this.COutstorebillupcd = COutstorebillupcd;
	}
	@XmlTransient
	public Date getDAcceptdatetime() {
		return this.DAcceptdatetime;
	}

	public void setDAcceptdatetime(Date DAcceptdatetime) {
		this.DAcceptdatetime = DAcceptdatetime;
	}
	@XmlTransient
	public String getCAccepttype() {
		return this.CAccepttype;
	}

	public void setCAccepttype(String CAccepttype) {
		this.CAccepttype = CAccepttype;
	}
	@XmlTransient
	public Integer getNDeelstatus() {
		return this.NDeelstatus;
	}

	public void setNDeelstatus(Integer NDeelstatus) {
		this.NDeelstatus = NDeelstatus;
	}
	@XmlTransient
	public Integer getNSendstatus() {
		return this.NSendstatus;
	}

	public void setNSendstatus(Integer NSendstatus) {
		this.NSendstatus = NSendstatus;
	}
	@XmlTransient
	public String getCSenddeptcd() {
		return this.CSenddeptcd;
	}

	public void setCSenddeptcd(String CSenddeptcd) {
		this.CSenddeptcd = CSenddeptcd;
	}
	@XmlTransient
	public String getCOutstorename() {
		return this.COutstorename;
	}

	public void setCOutstorename(String COutstorename) {
		this.COutstorename = COutstorename;
	}
	@XmlTransient
	public String getCAcceptdeptcd() {
		return this.CAcceptdeptcd;
	}

	public void setCAcceptdeptcd(String CAcceptdeptcd) {
		this.CAcceptdeptcd = CAcceptdeptcd;
	}
	@XmlTransient
	public String getCInstorename() {
		return this.CInstorename;
	}

	public void setCInstorename(String CInstorename) {
		this.CInstorename = CInstorename;
	}
	@XmlTransient
	public int getNAcceptcount() {
		return this.NAcceptcount;
	}

	public void setNAcceptcount(int NAcceptcount) {
		this.NAcceptcount = NAcceptcount;
	}
	@XmlTransient
	public Double getNDrugamount() {
		return this.NDrugamount;
	}

	public void setNDrugamount(Double NDrugamount) {
		this.NDrugamount = NDrugamount;
	}
	@XmlTransient
	public String getCAcceptopercd() {
		return this.CAcceptopercd;
	}

	public void setCAcceptopercd(String CAcceptopercd) {
		this.CAcceptopercd = CAcceptopercd;
	}
	@XmlTransient
	public String getCUptopercd() {
		return this.CUptopercd;
	}

	public void setCUptopercd(String CUptopercd) {
		this.CUptopercd = CUptopercd;
	}
	@XmlTransient
	public Date getDUptdatetime() {
		return this.DUptdatetime;
	}

	public void setDUptdatetime(Date DUptdatetime) {
		this.DUptdatetime = DUptdatetime;
	}
	@XmlTransient
	public String getCAcceptopername() {
		return this.CAcceptopername;
	}

	public void setCAcceptopername(String CAcceptopername) {
		this.CAcceptopername = CAcceptopername;
	}
	@XmlTransient
	public String getCUptopername() {
		return this.CUptopername;
	}

	public void setCUptopername(String CUptopername) {
		this.CUptopername = CUptopername;
	}
	@XmlTransient
	public String getCRemark() {
		return this.CRemark;
	}

	public void setCRemark(String CRemark) {
		this.CRemark = CRemark;
	}
	@XmlTransient
	public String getCAuditorname() {
		return this.CAuditorname;
	}

	public void setCAuditorname(String CAuditorname) {
		this.CAuditorname = CAuditorname;
	}
	@XmlTransient
	public String getCShelfuppeople() {
		return this.CShelfuppeople;
	}

	public void setCShelfuppeople(String CShelfuppeople) {
		this.CShelfuppeople = CShelfuppeople;
	}
	@XmlTransient
	public String getInstitution() {
		return this.institution;
	}

	public void setInstitution(String institution) {
		this.institution = institution;
	}
	@XmlTransient
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TSiipDruginstore))
			return false;
		TSiipDruginstore castOther = (TSiipDruginstore) other;

		return ((this.getCAcceptbillcd() == castOther.getCAcceptbillcd()) || (this
				.getCAcceptbillcd() != null
				&& castOther.getCAcceptbillcd() != null && this
				.getCAcceptbillcd().equals(castOther.getCAcceptbillcd())))
				&& ((this.getCreatorcd() == castOther.getCreatorcd()) || (this
						.getCreatorcd() != null
						&& castOther.getCreatorcd() != null && this
						.getCreatorcd().equals(castOther.getCreatorcd())))
				&& ((this.getCreatorname() == castOther.getCreatorname()) || (this
						.getCreatorname() != null
						&& castOther.getCreatorname() != null && this
						.getCreatorname().equals(castOther.getCreatorname())))
				&& ((this.getCreatetime() == castOther.getCreatetime()) || (this
						.getCreatetime() != null
						&& castOther.getCreatetime() != null && this
						.getCreatetime().equals(castOther.getCreatetime())))
				&& ((this.getCOutstorebillupcd() == castOther
						.getCOutstorebillupcd()) || (this
						.getCOutstorebillupcd() != null
						&& castOther.getCOutstorebillupcd() != null && this
						.getCOutstorebillupcd().equals(
								castOther.getCOutstorebillupcd())))
				&& ((this.getDAcceptdatetime() == castOther
						.getDAcceptdatetime()) || (this.getDAcceptdatetime() != null
						&& castOther.getDAcceptdatetime() != null && this
						.getDAcceptdatetime().equals(
								castOther.getDAcceptdatetime())))
				&& ((this.getCAccepttype() == castOther.getCAccepttype()) || (this
						.getCAccepttype() != null
						&& castOther.getCAccepttype() != null && this
						.getCAccepttype().equals(castOther.getCAccepttype())))
				&& (this.getNDeelstatus() == castOther.getNDeelstatus())
				&& (this.getNSendstatus() == castOther.getNSendstatus())
				&& ((this.getCSenddeptcd() == castOther.getCSenddeptcd()) || (this
						.getCSenddeptcd() != null
						&& castOther.getCSenddeptcd() != null && this
						.getCSenddeptcd().equals(castOther.getCSenddeptcd())))
				&& ((this.getCOutstorename() == castOther.getCOutstorename()) || (this
						.getCOutstorename() != null
						&& castOther.getCOutstorename() != null && this
						.getCOutstorename()
						.equals(castOther.getCOutstorename())))
				&& ((this.getCAcceptdeptcd() == castOther.getCAcceptdeptcd()) || (this
						.getCAcceptdeptcd() != null
						&& castOther.getCAcceptdeptcd() != null && this
						.getCAcceptdeptcd()
						.equals(castOther.getCAcceptdeptcd())))
				&& ((this.getCInstorename() == castOther.getCInstorename()) || (this
						.getCInstorename() != null
						&& castOther.getCInstorename() != null && this
						.getCInstorename().equals(castOther.getCInstorename())))
				&& (this.getNAcceptcount() == castOther.getNAcceptcount())
				&& ((this.getNDrugamount() == castOther.getNDrugamount()) || (this
						.getNDrugamount() != null
						&& castOther.getNDrugamount() != null && this
						.getNDrugamount().equals(castOther.getNDrugamount())))
				&& ((this.getCAcceptopercd() == castOther.getCAcceptopercd()) || (this
						.getCAcceptopercd() != null
						&& castOther.getCAcceptopercd() != null && this
						.getCAcceptopercd()
						.equals(castOther.getCAcceptopercd())))
				&& ((this.getCUptopercd() == castOther.getCUptopercd()) || (this
						.getCUptopercd() != null
						&& castOther.getCUptopercd() != null && this
						.getCUptopercd().equals(castOther.getCUptopercd())))
				&& ((this.getDUptdatetime() == castOther.getDUptdatetime()) || (this
						.getDUptdatetime() != null
						&& castOther.getDUptdatetime() != null && this
						.getDUptdatetime().equals(castOther.getDUptdatetime())))
				&& ((this.getCAcceptopername() == castOther
						.getCAcceptopername()) || (this.getCAcceptopername() != null
						&& castOther.getCAcceptopername() != null && this
						.getCAcceptopername().equals(
								castOther.getCAcceptopername())))
				&& ((this.getCUptopername() == castOther.getCUptopername()) || (this
						.getCUptopername() != null
						&& castOther.getCUptopername() != null && this
						.getCUptopername().equals(castOther.getCUptopername())))
				&& ((this.getCRemark() == castOther.getCRemark()) || (this
						.getCRemark() != null && castOther.getCRemark() != null && this
						.getCRemark().equals(castOther.getCRemark())))
				&& ((this.getCAuditorname() == castOther.getCAuditorname()) || (this
						.getCAuditorname() != null
						&& castOther.getCAuditorname() != null && this
						.getCAuditorname().equals(castOther.getCAuditorname())))
				&& ((this.getCShelfuppeople() == castOther.getCShelfuppeople()) || (this
						.getCShelfuppeople() != null
						&& castOther.getCShelfuppeople() != null && this
						.getCShelfuppeople().equals(
								castOther.getCShelfuppeople())))
				&& ((this.getInstitution() == castOther.getInstitution()) || (this
						.getInstitution() != null
						&& castOther.getInstitution() != null && this
						.getInstitution().equals(castOther.getInstitution())))
				&& ((this.getArea() == castOther.getArea()) || (this.getArea() != null
						&& castOther.getArea() != null && this.getArea()
						.equals(castOther.getArea())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCAcceptbillcd() == null ? 0 : this.getCAcceptbillcd()
						.hashCode());
		result = 37 * result
				+ (getCreatorcd() == null ? 0 : this.getCreatorcd().hashCode());
		result = 37
				* result
				+ (getCreatorname() == null ? 0 : this.getCreatorname()
						.hashCode());
		result = 37
				* result
				+ (getCreatetime() == null ? 0 : this.getCreatetime()
						.hashCode());
		result = 37
				* result
				+ (getCOutstorebillupcd() == null ? 0 : this
						.getCOutstorebillupcd().hashCode());
		result = 37
				* result
				+ (getDAcceptdatetime() == null ? 0 : this.getDAcceptdatetime()
						.hashCode());
		result = 37
				* result
				+ (getCAccepttype() == null ? 0 : this.getCAccepttype()
						.hashCode());
		result = 37 * result + this.getNDeelstatus();
		result = 37 * result + this.getNSendstatus();
		result = 37
				* result
				+ (getCSenddeptcd() == null ? 0 : this.getCSenddeptcd()
						.hashCode());
		result = 37
				* result
				+ (getCOutstorename() == null ? 0 : this.getCOutstorename()
						.hashCode());
		result = 37
				* result
				+ (getCAcceptdeptcd() == null ? 0 : this.getCAcceptdeptcd()
						.hashCode());
		result = 37
				* result
				+ (getCInstorename() == null ? 0 : this.getCInstorename()
						.hashCode());
		result = 37 * result + this.getNAcceptcount();
		result = 37
				* result
				+ (getNDrugamount() == null ? 0 : this.getNDrugamount()
						.hashCode());
		result = 37
				* result
				+ (getCAcceptopercd() == null ? 0 : this.getCAcceptopercd()
						.hashCode());
		result = 37
				* result
				+ (getCUptopercd() == null ? 0 : this.getCUptopercd()
						.hashCode());
		result = 37
				* result
				+ (getDUptdatetime() == null ? 0 : this.getDUptdatetime()
						.hashCode());
		result = 37
				* result
				+ (getCAcceptopername() == null ? 0 : this.getCAcceptopername()
						.hashCode());
		result = 37
				* result
				+ (getCUptopername() == null ? 0 : this.getCUptopername()
						.hashCode());
		result = 37 * result
				+ (getCRemark() == null ? 0 : this.getCRemark().hashCode());
		result = 37
				* result
				+ (getCAuditorname() == null ? 0 : this.getCAuditorname()
						.hashCode());
		result = 37
				* result
				+ (getCShelfuppeople() == null ? 0 : this.getCShelfuppeople()
						.hashCode());
		result = 37
				* result
				+ (getInstitution() == null ? 0 : this.getInstitution()
						.hashCode());
		result = 37 * result
				+ (getArea() == null ? 0 : this.getArea().hashCode());
		return result;
	}

}
