package com.simlink.task.entity;

// Generated 2016-10-3 9:10:20 by Hibernate Tools 3.2.2.GA

import java.io.Serializable;
import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlRootElement;  
import javax.xml.bind.annotation.XmlAccessType;  
import javax.xml.bind.annotation.XmlAccessorType;  
import javax.xml.bind.annotation.XmlElement;  
import javax.xml.bind.annotation.XmlElementWrapper;  
import javax.xml.bind.annotation.XmlRootElement;  
import javax.xml.bind.annotation.XmlType; 
import javax.xml.bind.annotation.XmlTransient;
/**
 * TSiipDrugoutstoreId generated by hbm2java
 */
@SuppressWarnings({ "restriction", "unused", "serial" })
@XmlRootElement(name = "row")
public class TSiipDrugoutstore implements java.io.Serializable {

	@XmlElement(name = "C_OUTBILLCD")
	private String COutbillcd;
	
	@XmlElement(name = "CREATORCD")
	private String creatorcd;
	
	@XmlElement(name = "CREATORNAME")
	private String creatorname;
	
	@XmlElement(name = "CREATETIME")
	private Date createtime;
	
	@XmlElement(name = "C_INSTOREBILLUPCD")
	private String CInstorebillupcd;
	
	@XmlElement(name = "D_OUTDATETIME")
	private Date DOutdatetime;
	
	@XmlElement(name = "C_OUTTYPE")
	private String COuttype;
	
	@XmlElement(name = "N_DEELSTATUS")
	private Integer NDeelstatus;
	
	@XmlElement(name = "N_SENDSTATUS")
	private Integer NSendstatus;
	
	@XmlElement(name = "C_ACCEPTDEPTCD")
	private String CAcceptdeptcd;
	
	@XmlElement(name = "C_ACCEPTDEPTNAME")
	private String CAcceptdeptname;
	
	@XmlElement(name = "C_OUTDEPTCD")
	private String COutdeptcd;
	
	@XmlElement(name = "C_OUTDEPTNAME")
	private String COutdeptname;
	
	@XmlElement(name = "N_OUTCOUNT")
	private Integer NOutcount;
	
	@XmlElement(name = "N_DRUGAMOUNT")
	private Double NDrugamount;
	
	@XmlElement(name = "C_OUTOPERCD")
	private String COutopercd;
	
	@XmlElement(name = "C_ACCEPTOPERCD")
	private String CAcceptopercd;
	
	@XmlElement(name = "C_UPTOPERCD")
	private String CUptopercd;
	
	@XmlElement(name = "D_UPTDATETIME")
	private Date DUptdatetime;
	
	@XmlElement(name = "C_OUTOPERNAME")
	private String COutopername;
	
	@XmlElement(name = "C_ACCEPTOPERNAME")
	private String CAcceptopername;
	
	@XmlElement(name = "C_UPTOPERNAME")
	private String CUptopername;
	
	@XmlElement(name = "C_REMARK")
	private String CRemark;
	
	@XmlElement(name = "C_AUDITORNAME")
	private String CAuditorname;
	
	@XmlElement(name = "C_SHELFDOWNPEOPLE")
	private String CShelfdownpeople;
	
	@XmlElement(name = "ID")
	private String institution;
	
	@XmlElement(name = "ID")
	private String area;

	public TSiipDrugoutstore() {
		super();
	}

	public TSiipDrugoutstore(String COutbillcd, String creatorcd,
			String creatorname, Date createtime,
			String CInstorebillupcd, Date DOutdatetime,
			String COuttype, Integer NDeelstatus, Integer NSendstatus,
			String CAcceptdeptcd, String CAcceptdeptname,
			String COutdeptcd, String COutdeptname, Integer NOutcount,
			Double NDrugamount, String institution, String area) {
		this.COutbillcd = COutbillcd;
		this.creatorcd = creatorcd;
		this.creatorname = creatorname;
		this.createtime = createtime;
		this.CInstorebillupcd = CInstorebillupcd;
		this.DOutdatetime = DOutdatetime;
		this.COuttype = COuttype;
		this.NDeelstatus = NDeelstatus;
		this.NSendstatus = NSendstatus;
		this.CAcceptdeptcd = CAcceptdeptcd;
		this.CAcceptdeptname = CAcceptdeptname;
		this.COutdeptcd = COutdeptcd;
		this.COutdeptname = COutdeptname;
		this.NOutcount = NOutcount;
		this.NDrugamount = NDrugamount;
		this.institution = institution;
		this.area = area;
	}

	public TSiipDrugoutstore(String COutbillcd, String creatorcd,
			String creatorname, Date createtime,
			String CInstorebillupcd, Date DOutdatetime,
			String COuttype, Integer NDeelstatus, Integer NSendstatus,
			String CAcceptdeptcd, String CAcceptdeptname,
			String COutdeptcd, String COutdeptname, Integer NOutcount,
			Double NDrugamount, String COutopercd,
			String CAcceptopercd, String CUptopercd,
			Date DUptdatetime, String COutopername,
			String CAcceptopername, String CUptopername,
			String CRemark, String CAuditorname,
			String CShelfdownpeople, String institution, String area) {
		this.COutbillcd = COutbillcd;
		this.creatorcd = creatorcd;
		this.creatorname = creatorname;
		this.createtime = createtime;
		this.CInstorebillupcd = CInstorebillupcd;
		this.DOutdatetime = DOutdatetime;
		this.COuttype = COuttype;
		this.NDeelstatus = NDeelstatus;
		this.NSendstatus = NSendstatus;
		this.CAcceptdeptcd = CAcceptdeptcd;
		this.CAcceptdeptname = CAcceptdeptname;
		this.COutdeptcd = COutdeptcd;
		this.COutdeptname = COutdeptname;
		this.NOutcount = NOutcount;
		this.NDrugamount = NDrugamount;
		this.COutopercd = COutopercd;
		this.CAcceptopercd = CAcceptopercd;
		this.CUptopercd = CUptopercd;
		this.DUptdatetime = DUptdatetime;
		this.COutopername = COutopername;
		this.CAcceptopername = CAcceptopername;
		this.CUptopername = CUptopername;
		this.CRemark = CRemark;
		this.CAuditorname = CAuditorname;
		this.CShelfdownpeople = CShelfdownpeople;
		this.institution = institution;
		this.area = area;
	}
	@XmlTransient
	public String getCOutbillcd() {
		return this.COutbillcd;
	}

	public void setCOutbillcd(String COutbillcd) {
		this.COutbillcd = COutbillcd;
	}
	@XmlTransient
	public String getCreatorcd() {
		return this.creatorcd;
	}

	public void setCreatorcd(String creatorcd) {
		this.creatorcd = creatorcd;
	}
	@XmlTransient
	public String getCreatorname() {
		return this.creatorname;
	}

	public void setCreatorname(String creatorname) {
		this.creatorname = creatorname;
	}
	@XmlTransient
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}
	@XmlTransient
	public String getCInstorebillupcd() {
		return this.CInstorebillupcd;
	}

	public void setCInstorebillupcd(String CInstorebillupcd) {
		this.CInstorebillupcd = CInstorebillupcd;
	}
	@XmlTransient
	public Date getDOutdatetime() {
		return this.DOutdatetime;
	}

	public void setDOutdatetime(Date DOutdatetime) {
		this.DOutdatetime = DOutdatetime;
	}
	@XmlTransient
	public String getCOuttype() {
		return this.COuttype;
	}

	public void setCOuttype(String COuttype) {
		this.COuttype = COuttype;
	}
	@XmlTransient
	public Integer getNDeelstatus() {
		return this.NDeelstatus;
	}

	public void setNDeelstatus(Integer NDeelstatus) {
		this.NDeelstatus = NDeelstatus;
	}
	@XmlTransient
	public Integer getNSendstatus() {
		return this.NSendstatus;
	}

	public void setNSendstatus(Integer NSendstatus) {
		this.NSendstatus = NSendstatus;
	}
	@XmlTransient
	public String getCAcceptdeptcd() {
		return this.CAcceptdeptcd;
	}

	public void setCAcceptdeptcd(String CAcceptdeptcd) {
		this.CAcceptdeptcd = CAcceptdeptcd;
	}
	@XmlTransient
	public String getCAcceptdeptname() {
		return this.CAcceptdeptname;
	}

	public void setCAcceptdeptname(String CAcceptdeptname) {
		this.CAcceptdeptname = CAcceptdeptname;
	}
	@XmlTransient
	public String getCOutdeptcd() {
		return this.COutdeptcd;
	}

	public void setCOutdeptcd(String COutdeptcd) {
		this.COutdeptcd = COutdeptcd;
	}
	@XmlTransient
	public String getCOutdeptname() {
		return this.COutdeptname;
	}

	public void setCOutdeptname(String COutdeptname) {
		this.COutdeptname = COutdeptname;
	}
	@XmlTransient
	public Integer getNOutcount() {
		return this.NOutcount;
	}

	public void setNOutcount(Integer NOutcount) {
		this.NOutcount = NOutcount;
	}
	@XmlTransient
	public Double getNDrugamount() {
		return this.NDrugamount;
	}

	public void setNDrugamount(Double NDrugamount) {
		this.NDrugamount = NDrugamount;
	}
	@XmlTransient
	public String getCOutopercd() {
		return this.COutopercd;
	}

	public void setCOutopercd(String COutopercd) {
		this.COutopercd = COutopercd;
	}
	@XmlTransient
	public String getCAcceptopercd() {
		return this.CAcceptopercd;
	}

	public void setCAcceptopercd(String CAcceptopercd) {
		this.CAcceptopercd = CAcceptopercd;
	}
	@XmlTransient
	public String getCUptopercd() {
		return this.CUptopercd;
	}

	public void setCUptopercd(String CUptopercd) {
		this.CUptopercd = CUptopercd;
	}
	@XmlTransient
	public Date getDUptdatetime() {
		return this.DUptdatetime;
	}

	public void setDUptdatetime(Date DUptdatetime) {
		this.DUptdatetime = DUptdatetime;
	}
	@XmlTransient
	public String getCOutopername() {
		return this.COutopername;
	}

	public void setCOutopername(String COutopername) {
		this.COutopername = COutopername;
	}
	@XmlTransient
	public String getCAcceptopername() {
		return this.CAcceptopername;
	}

	public void setCAcceptopername(String CAcceptopername) {
		this.CAcceptopername = CAcceptopername;
	}
	@XmlTransient
	public String getCUptopername() {
		return this.CUptopername;
	}

	public void setCUptopername(String CUptopername) {
		this.CUptopername = CUptopername;
	}
	@XmlTransient
	public String getCRemark() {
		return this.CRemark;
	}

	public void setCRemark(String CRemark) {
		this.CRemark = CRemark;
	}
	@XmlTransient
	public String getCAuditorname() {
		return this.CAuditorname;
	}

	public void setCAuditorname(String CAuditorname) {
		this.CAuditorname = CAuditorname;
	}
	@XmlTransient
	public String getCShelfdownpeople() {
		return this.CShelfdownpeople;
	}

	public void setCShelfdownpeople(String CShelfdownpeople) {
		this.CShelfdownpeople = CShelfdownpeople;
	}
	@XmlTransient
	public String getInstitution() {
		return this.institution;
	}

	public void setInstitution(String institution) {
		this.institution = institution;
	}
	@XmlTransient
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TSiipDrugoutstore))
			return false;
		TSiipDrugoutstore castOther = (TSiipDrugoutstore) other;

		return ((this.getCOutbillcd() == castOther.getCOutbillcd()) || (this
				.getCOutbillcd() != null && castOther.getCOutbillcd() != null && this
				.getCOutbillcd().equals(castOther.getCOutbillcd())))
				&& ((this.getCreatorcd() == castOther.getCreatorcd()) || (this
						.getCreatorcd() != null
						&& castOther.getCreatorcd() != null && this
						.getCreatorcd().equals(castOther.getCreatorcd())))
				&& ((this.getCreatorname() == castOther.getCreatorname()) || (this
						.getCreatorname() != null
						&& castOther.getCreatorname() != null && this
						.getCreatorname().equals(castOther.getCreatorname())))
				&& ((this.getCreatetime() == castOther.getCreatetime()) || (this
						.getCreatetime() != null
						&& castOther.getCreatetime() != null && this
						.getCreatetime().equals(castOther.getCreatetime())))
				&& ((this.getCInstorebillupcd() == castOther
						.getCInstorebillupcd()) || (this.getCInstorebillupcd() != null
						&& castOther.getCInstorebillupcd() != null && this
						.getCInstorebillupcd().equals(
								castOther.getCInstorebillupcd())))
				&& ((this.getDOutdatetime() == castOther.getDOutdatetime()) || (this
						.getDOutdatetime() != null
						&& castOther.getDOutdatetime() != null && this
						.getDOutdatetime().equals(castOther.getDOutdatetime())))
				&& ((this.getCOuttype() == castOther.getCOuttype()) || (this
						.getCOuttype() != null
						&& castOther.getCOuttype() != null && this
						.getCOuttype().equals(castOther.getCOuttype())))
				&& (this.getNDeelstatus() == castOther.getNDeelstatus())
				&& (this.getNSendstatus() == castOther.getNSendstatus())
				&& ((this.getCAcceptdeptcd() == castOther.getCAcceptdeptcd()) || (this
						.getCAcceptdeptcd() != null
						&& castOther.getCAcceptdeptcd() != null && this
						.getCAcceptdeptcd()
						.equals(castOther.getCAcceptdeptcd())))
				&& ((this.getCAcceptdeptname() == castOther
						.getCAcceptdeptname()) || (this.getCAcceptdeptname() != null
						&& castOther.getCAcceptdeptname() != null && this
						.getCAcceptdeptname().equals(
								castOther.getCAcceptdeptname())))
				&& ((this.getCOutdeptcd() == castOther.getCOutdeptcd()) || (this
						.getCOutdeptcd() != null
						&& castOther.getCOutdeptcd() != null && this
						.getCOutdeptcd().equals(castOther.getCOutdeptcd())))
				&& ((this.getCOutdeptname() == castOther.getCOutdeptname()) || (this
						.getCOutdeptname() != null
						&& castOther.getCOutdeptname() != null && this
						.getCOutdeptname().equals(castOther.getCOutdeptname())))
				&& (this.getNOutcount() == castOther.getNOutcount())
				&& ((this.getNDrugamount() == castOther.getNDrugamount()) || (this
						.getNDrugamount() != null
						&& castOther.getNDrugamount() != null && this
						.getNDrugamount().equals(castOther.getNDrugamount())))
				&& ((this.getCOutopercd() == castOther.getCOutopercd()) || (this
						.getCOutopercd() != null
						&& castOther.getCOutopercd() != null && this
						.getCOutopercd().equals(castOther.getCOutopercd())))
				&& ((this.getCAcceptopercd() == castOther.getCAcceptopercd()) || (this
						.getCAcceptopercd() != null
						&& castOther.getCAcceptopercd() != null && this
						.getCAcceptopercd()
						.equals(castOther.getCAcceptopercd())))
				&& ((this.getCUptopercd() == castOther.getCUptopercd()) || (this
						.getCUptopercd() != null
						&& castOther.getCUptopercd() != null && this
						.getCUptopercd().equals(castOther.getCUptopercd())))
				&& ((this.getDUptdatetime() == castOther.getDUptdatetime()) || (this
						.getDUptdatetime() != null
						&& castOther.getDUptdatetime() != null && this
						.getDUptdatetime().equals(castOther.getDUptdatetime())))
				&& ((this.getCOutopername() == castOther.getCOutopername()) || (this
						.getCOutopername() != null
						&& castOther.getCOutopername() != null && this
						.getCOutopername().equals(castOther.getCOutopername())))
				&& ((this.getCAcceptopername() == castOther
						.getCAcceptopername()) || (this.getCAcceptopername() != null
						&& castOther.getCAcceptopername() != null && this
						.getCAcceptopername().equals(
								castOther.getCAcceptopername())))
				&& ((this.getCUptopername() == castOther.getCUptopername()) || (this
						.getCUptopername() != null
						&& castOther.getCUptopername() != null && this
						.getCUptopername().equals(castOther.getCUptopername())))
				&& ((this.getCRemark() == castOther.getCRemark()) || (this
						.getCRemark() != null && castOther.getCRemark() != null && this
						.getCRemark().equals(castOther.getCRemark())))
				&& ((this.getCAuditorname() == castOther.getCAuditorname()) || (this
						.getCAuditorname() != null
						&& castOther.getCAuditorname() != null && this
						.getCAuditorname().equals(castOther.getCAuditorname())))
				&& ((this.getCShelfdownpeople() == castOther
						.getCShelfdownpeople()) || (this.getCShelfdownpeople() != null
						&& castOther.getCShelfdownpeople() != null && this
						.getCShelfdownpeople().equals(
								castOther.getCShelfdownpeople())))
				&& ((this.getInstitution() == castOther.getInstitution()) || (this
						.getInstitution() != null
						&& castOther.getInstitution() != null && this
						.getInstitution().equals(castOther.getInstitution())))
				&& ((this.getArea() == castOther.getArea()) || (this.getArea() != null
						&& castOther.getArea() != null && this.getArea()
						.equals(castOther.getArea())));
	}


}
